name: Deploy
on: workflow_dispatch

env:
  REGISTRY: ${{ secrets.GCP_REGISTRY }}
  IMAGE: $REGISTRY/progressium-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auth gcloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Setup gcloud sdk
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Build docker image
        run: docker build . -t $IMAGE

      - name: Publish to the container registry
        run: docker push $IMAGE
