name: Deploy
on:
  push: #pull_request
    branches:
      - release

env:
  IMAGE: ${{ secrets.GCP_REGISTRY }}/progressium-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auth gcloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure docker
        run: gcloud auth configure-docker

      - name: Build docker image
        run: docker build . -t $IMAGE

      - name: Publish to the container registry
        run: docker push $IMAGE

      - name: Deploy the container
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "progressium-api"
          image: ${{env.IMAGE}}
