name: Deploy
on: workflow_dispatch

env:
  REGISTRY: ${{ secrets.GCP_REGISTRY }}
  IMAGE: $REGISTRY/progressium-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_KEY }}

      - name: Authenticate gcloud
        run: gcloud auth configure-docker

      - name: Build docker image
        run: docker build . -t $IMAGE

      - name: Publish to the container registry
        run: docker push $IMAGE
