name: Deploy
on: workflow_dispatch

env:
  IMAGE: ${{ secrets.GCP_REGISTRY }}/progressium-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auth gcloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Configure docker
        run: gcloud auth configure-docker

      - name: Build docker image
        run: docker build . -t $IMAGE:latest

      - name: Publish to the container registry
        run: docker push $IMAGE:latest
